name: Peterpillsbury
favicon: null
layout_spectrum: 1
title: Peter Pillsbury
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b74e39'
    - '#f8f8f8'
    - '#efe2df'
    - '#daa9a0'
    - '#c77868'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
